feat: Add styleing for darkmode
denoland/deno_lint pull request #1068
Opened 2022-08-15 22:16 UTC by littletof

Add darkmode support for the site.

The diff on github looks worst than what actually changed.

<details>
<summary>Previous</summary>

![image](https://user-images.githubusercontent.com/32012862/184727476-91d758a6-068f-4d49-afe3-a49f882b5c85.png)

</details>

Now:

![image](https://user-images.githubusercontent.com/32012862/184727045-a4182779-6b5f-4d90-8667-8088b220bf87.png)

2022-08-15 22:17 UTC, littletof commented
Not fully sold on the searchbar styleing, but it works as a start anyways.

2022-08-22 10:00 UTC, littletof commented
@hashrock Not urgent, but can you please review this PR and #1066?
These should fix darkmode and markdown styleing together with the #1067.

2022-08-22 13:41 UTC, bartlomieju commented
Opened https://github.com/denoland/deno_lint/pull/1069

2022-08-22 16:55 UTC, hashrock requested changes
very clean darkmode theme!
I found a small accessibility issue here

2022-08-22 16:55 UTC, hashrock commented on www/pages/index.tsx
> +          <div class={tw`mt-6 text-gray-600`}>
```suggestion
          <div class={tw`mt-6 text-gray-600 dark:text-gray-400`}>
```

Not enough contrast here:
![image](https://user-images.githubusercontent.com/3132889/185976014-87667e1a-7e1e-4353-908e-a116a8757f09.png)

2022-08-22 17:51 UTC, littletof commented
@hashrock Right, thanks, fixed it with your suggestion. Looks better now.

2022-09-02 17:00 UTC, littletof commented
@hashrock @bartlomieju can this be merged?

2022-09-02 17:24 UTC, merged