doc: Add linting hints and docs
denoland/deno_lint pull request #554
Opened 2020-12-01 22:05 UTC by cknight

This PR contributes to #159 by adding linting hints and docs to:
* no_irregular_whitespace
* no_misued_new

2020-12-02 13:36 UTC, magurotuna requested changes

2020-12-02 13:36 UTC, magurotuna commented on src/rules/no_irregular_whitespace.rs
> +        ],
```suggestion
      ],
```

Looks like more indent than it should have

2020-12-02 13:36 UTC, magurotuna commented on src/rules/no_misused_new.rs
> +}
```suggestion
class C {
  constructor() {}
}

interface I {
  new (): C;
}
```


a very minor nit, but it'd be nice to have a blank line between `C` and `I` as the `Invalid` example has 👍

2020-12-03 14:52 UTC, magurotuna approved these changes
LGTM 👍  nice doc!

2020-12-03 16:09 UTC, bartlomieju approved these changes
LGTM, thanks you @cknight!

2020-12-03 16:09 UTC, merged